### PR TITLE
Stop downloading files from COSA on each run

### LINKED ISSUE #20: Don't fetch files directly from github during runtime
I have seen many direct github downloads fail in the past weeks, github seems now to heavily rate limit downloads:
https://github.blog/changelog/2025-05-08-updated-rate-limits-for-unauthenticated-requests/

This script makes use of several direct downloads which thus can fail now

https://github.com/coreos/custom-coreos-disk-images/blob/561349037d798c14c12b77523d1320bbfb903f34/custom-coreos-disk-images.sh#L194-L198

And this is not just theoretical, it hit us quite hard two weeks ago, example log: https://cirrus-ci.com/task/4867550770626560 and I see it also a lot in our buildah tests

So would it better to vendor such file directly here and update them? They are pinned via commit anyway so it is not like it was a moving target before.

Now for podman-machine-os we still download this script here in a similar manner so we would then need to vendor this repo as well there, not sure if this is a particular elegant solution. I am open to other suggestions but I think in the long run keeping these direct downloads will result in to many flakes.

### PR DESCRIPTION
**Pull request by dustymabe**
Let's just import the files we need into this repo. A submodule here could have worked, but there is a lot in COSA we actually don't want to clone so this is a poor man's version of a submodule.

Fixes https://github.com/coreos/custom-coreos-disk-images/issues/20

### CODE REVIEW

File: sync-cosa-imports.sh [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+    url=$1
+    filename=$(basename "${url}")
+    echo "# Synced from ${url}" > "${filename}"
+    curl -L --no-progress-meter --fail "${url}" >> "${filename}"
+}
+
+pushd cosa-imports
+get_url "${COSA_GIT_REPO_URL}/src/runvm-osbuild"
+chmod +x runvm-osbuild
+for manifest in "coreos.osbuild.${ARCH}.mpp.yaml" ${PLATFORM_FILENAMES}; do
```
Comment (Luap99) [inline sync-cosa-imports.sh]: should this pull the file for all supported coreos arches not just the local one where you ran the script?

Just a guess but I assume `coreos.osbuild.aarch64.mpp.yaml` is missing and  that means our aarch64 build would fail?

**Review by Luap99 — COMMENTED** [review]
Thanks, one point where I am not sure about

File: sync-cosa-imports.sh (hunk 1 above)
Comment (dustymabe) [reply sync-cosa-imports.sh]: ~hmm. cross building isn't really supported I don't think.~

~Are you telling me you are running aarch64 builds on an x86_64 platform?~

Comment (dustymabe) [reply sync-cosa-imports.sh]: ahh I see. Yes; let me fix that. Good catch

Comment (dustymabe) [reply sync-cosa-imports.sh]: Fixed.

**Comment by dustymabe** [comment]
In the new upload I bumped the COSA commit (needed because riscv64 was added later than the commit we had previously pinned to.

**Review by Luap99 — APPROVED** [review]
LGTM

**Review by marmijo — APPROVED** [review]
LGTM
